language: go

go:
    - 1.16.x

env: GO111MODULE=on

services: docker

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

script:
    - make fmt-check
    - make lint
    - make test

jobs:
    include:
        - stage: Check
          name: Go Format Check
          script: make fmt-check
        - name: Lint
          script: make lint
        - stage: Test
          name: Unit test
          script: make test
        - stage: Build and Run Docker
          name: Build and Run Integration test
          script:
              - docker build --rm -t dcard-ratelimit-middleware .
              - docker-compose up -d
              - docker ps
              - make integration-test
