version: '3'
services:
    redis:
        image: 'redis'
        environment:
            REDIS_PASSWORD: yourpassword
        restart: always
        ports:
            - "6379:6379"
    api:
        image: 'dcard-ratelimit-middleware'
        build: ./
        environment:
            REDIS_ADDR: redis:6379
            REDIS_PASSWORD: yourpassword
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - redis
